### PR TITLE
Add websocket feature

### PR DESCRIPTION
**Pull request by wuhugh**
Added sockets to the backend and so far to Host.vue. If you open up the app you should be able to add songs and change the votes, but it resets when you refresh or someone else connects (lol). Still need to add separate rooms and update Guest.vue.

### CODE REVIEW

**Comment by rajputd** [comment]
I can't seem to get the player to work anymore. I can add songs but the play button doesn't seem to do anything for me. Besides that the socket-io stuff looks good.

**Comment by rajputd** [comment]
I found the issue. Did you include all the files you modified when you made the second commit? Inside PlayerBar.vue I found that changing `this.player.ytPlayer.loadVideoById(this.roomPlaylist[0].id.videoId, 0, "small");` to `this.player.ytPlayer.loadVideoById(this.roomPlaylist[0].videoItem.id.videoId, 0, "small");` inside the `playVideo` method did the trick.

**Comment by wuhugh** [comment]
I've added the videoItem property and it plays for me. Let me know if it is working on your end.

**Comment by rajputd** [comment]
Everything worked for me.

**Comment by rajputd** [comment]
I don't know if you still wan't this branch so I'll leave it up to you to delete.

**Pull request merged**
